# Generated by Django 2.2rc1 on 2019-03-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=200)),
            ],
        ),
    ]
