# Generated by Django 2.2rc1 on 2019-04-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Phone_number', models.CharField(max_length=100)),
                ('Looking_for', models.CharField(choices=[('AP', 'Apartment (2/3 BHK)'), ('Villa', 'Villa / Independent house'), ('Re', 'Residental Plot'), ('Ag', 'Agriculture Plot')], max_length=100)),
                ('AreaPreferred', models.CharField(max_length=100)),
                ('Budget', models.CharField(max_length=100)),
            ],
        ),
    ]
